# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apex < Formula
  desc "AI-powered software delivery agent"
  homepage "https://github.com/Inventeer/apex"
  version "0.32.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.32.0/apex_0.32.0_darwin_amd64.tar.gz"
      sha256 "90758db0ee638700aa2bd274a8b032d8e8314e2bd22219906638c0e8a0c4d10f"

      define_method(:install) do
        bin.install "apex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.32.0/apex_0.32.0_darwin_arm64.tar.gz"
      sha256 "ad6a9c9de89a47d49ee118a65f570c31e07c6974393b7e4d1946e1cfe43256bd"

      define_method(:install) do
        bin.install "apex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.32.0/apex_0.32.0_linux_amd64.tar.gz"
      sha256 "5ae51e63a75385d74dc0e4522389329a1429e15085208e812ce51a4a89025516"
      define_method(:install) do
        bin.install "apex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.32.0/apex_0.32.0_linux_arm64.tar.gz"
      sha256 "283e9f1b14d67548d23803cf7adb004a9c87675694181b5d9f1b750669d9c82f"
      define_method(:install) do
        bin.install "apex"
      end
    end
  end

  test do
    system "#{bin}/apex", "version"
  end
end
