# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apex < Formula
  desc "AI-powered software delivery agent"
  homepage "https://github.com/Inventeer/apex"
  version "0.31.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.31.0/apex_0.31.0_darwin_amd64.tar.gz"
      sha256 "85bb4e12de6761d45f7746ea57e28c4f2ff788995709e14c18ea766d05ad3142"

      define_method(:install) do
        bin.install "apex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.31.0/apex_0.31.0_darwin_arm64.tar.gz"
      sha256 "8fd07b33feebba3cb0b4235dbacf0743768f8198f26bd9d899e26bd12ea55eb7"

      define_method(:install) do
        bin.install "apex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.31.0/apex_0.31.0_linux_amd64.tar.gz"
      sha256 "9b426d3e9752ad9d153579ba4796ce38edfae721f841b7b58e26c995201f4bf9"
      define_method(:install) do
        bin.install "apex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.31.0/apex_0.31.0_linux_arm64.tar.gz"
      sha256 "69e0f91ce62087fd7a015deafda4127274aa39a64bc03f42ccefc553fe39da96"
      define_method(:install) do
        bin.install "apex"
      end
    end
  end

  test do
    system "#{bin}/apex", "version"
  end
end
