# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apex < Formula
  desc "AI-powered software delivery agent"
  homepage "https://github.com/Inventeer/apex"
  version "0.30.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.30.0/apex_0.30.0_darwin_amd64.tar.gz"
      sha256 "e3662ea8c7f615658967c1385ed0f7fefcfe0ade833648e637fc6f1d6551cea8"

      define_method(:install) do
        bin.install "apex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.30.0/apex_0.30.0_darwin_arm64.tar.gz"
      sha256 "662cae948ee2f791d49378a5a80669694904a2edc7190d0322c95814a096f286"

      define_method(:install) do
        bin.install "apex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.30.0/apex_0.30.0_linux_amd64.tar.gz"
      sha256 "0f58280101ab30ee7911bea88a71469f89fcf3a5267b7338dd693ed81a01f199"
      define_method(:install) do
        bin.install "apex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inventeer/apex-releases/releases/download/v0.30.0/apex_0.30.0_linux_arm64.tar.gz"
      sha256 "98e85ffc1adda491f74329f81aed04a57b4ec026546cd6f1ed77b70c54445a0a"
      define_method(:install) do
        bin.install "apex"
      end
    end
  end

  test do
    system "#{bin}/apex", "version"
  end
end
